/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package fisher.parser.json;

public interface JsonParserConstants {

  int EOF = 0;
  int PLUS = 5;
  int MINUS = 6;
  int DOT = 7;
  int COMMA = 8;
  int COLON = 9;
  int TRUE = 10;
  int FALSE = 11;
  int NULL = 12;
  int DIGITS = 13;
  int E = 14;
  int LBRACKET = 15;
  int RBRACKET = 16;
  int LBRACE = 17;
  int RBRACE = 18;
  int STRING = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\",\"",
    "\":\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<DIGITS>",
    "<E>",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "<STRING>",
  };

}
